[package]
name = "blaze-tests"
version = "0.1.0"
edition = "2021"
resolver = "1"

[features]
default = ["tokio/rt-multi-thread"]


[dependencies]
ahash = "0.8"
arrow = { workspace = true }
async-trait = "0.1.74"
base64 = "0.21.5"
bytes = "1.4.0"
blaze-jni-bridge = { workspace = true }
bytesize = "1.1.0"
datafusion = { workspace = true }
datafusion-ext-commons = { workspace = true }
datafusion-ext-exprs = { workspace = true }
datafusion-ext-plans = { workspace = true }
derivative = "2.2.0"
futures = "0.3"
hashbrown = "0.14.2"
itertools = "0.10.3"
jni = { version = "0.20.0", features = ["invocation"] }
log = "0.4.14"
lz4_flex = "0.11.1"
num = "0.4.0"
object_store = "0.6.1"
once_cell = "1.16.0"
panic-message = "0.3.0"
parking_lot = "0.12.1"
paste = "1.0.7"
tempfile = "3"
tokio = "1.19"
zstd = "0.12.3"
#walkdir = { version = "2.4.0", features = [] }

[dev-dependencies]
rand = "0.8.5"

[build-dependencies.walkdir]
version = "2"
